### ISSUE TITLE
fix: TS6133 unused 'whenReadyHandler' in src/main/__tests__/index.test.ts

### ISSUE THREAD

**Issue by nguyenerapp** [nguyenerapp/boss-companion#92]
## Problem
`npx tsc --noEmit` fails on main HEAD (63d9938) with:

```
src/main/__tests__/index.test.ts(153,11): error TS6133: 'whenReadyHandler' is declared but its value is never read.
```

Introduced by #89 (test: add unit tests for main process IPC handlers and window management).

## Acceptance
- `npx tsc --noEmit` exits 0
- Either use the variable or prefix with underscore (`_whenReadyHandler`) per TS convention

## Found by
companion-review slot 2026-04-19 04:30 PT
